services:
  backend:
    build:
      context: ./backend
    container_name: estoque_backend
    restart: unless-stopped
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: estoque_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
